const mongoose = require('mongoose');

const commonStringFields = (dataType, isRequired, isUnique) => ({
     type: dataType,
     required: isRequired,
     unique: isUnique,
});
const commonNumberFields = (dataType, isRequired) => ({
     type: dataType,
     required: isRequired,
     default: 0
});

const matchSchema = new mongoose.Schema(
     {
          "date": { type: Date, required: false, default: "", unique: false },
          "venue": { type: String, required: false, default: "", unique: false },
          "result": { type: String, required: false, default: "", unique: false },
          "playerOfTheMatch": { type: String, required: false, default: "", unique: false },
          "innings": [
               {
                    "teamA": { type: String, required: false, default: "", unique: false },
                    "score": {
                         "overs": { type: Number, required: false, default: 0, unique: false },
                         "wickets": { type: Number, required: false, default: 0, unique: false },
                         "total": { type: Number, required: false, default: 0, unique: false },
                    },
                    "players": [
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                    ]
               },
               {
                    "teamB": { type: String, required: false, default: "", unique: false },
                    "score": {
                         "overs": { type: Number, required: false, default: 0, unique: false },
                         "wickets": { type: Number, required: false, default: 0, unique: false },
                         "total": { type: Number, required: false, default: 0, unique: false },
                    },
                    "players": [
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         },
                         {
                              "name": { type: String, required: false, default: "", unique: false },
                              "runs": { type: Number, required: false, default: 0, unique: false },
                              "balls": { type: Number, required: false, default: 0, unique: false },
                              "strikeRate": { type: Number, required: false, default: 0, unique: false },
                              "sixes": { type: Number, required: false, default: 0, unique: false },
                              "fours": { type: Number, required: false, default: 0, unique: false },
                              "1s": { type: Number, required: false, default: 0, unique: false },
                              "2s": { type: Number, required: false, default: 0, unique: false },
                              "3s": { type: Number, required: false, default: 0, unique: false },
                         }
                    ]
               }
          ]

     }

);

const Match = mongoose.model('Match', matchSchema);

module.exports = Match;


